# Generated by Django 3.2.9 on 2022-01-11 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerSno', models.AutoField(primary_key=True, serialize=False)),
                ('answerOfQue', models.IntegerField()),
                ('answerDesc', models.TextField()),
                ('answeredBy', models.TextField()),
                ('answeredOn', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('queSno', models.AutoField(primary_key=True, serialize=False)),
                ('questionShortDesc', models.TextField()),
                ('questionLongDesc', models.TextField()),
                ('askedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('noOfAnswers', models.IntegerField(default=0)),
                ('askedBy', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('tags', models.TextField()),
            ],
        ),
    ]
