# Generated by Django 3.2.9 on 2022-01-17 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replySno', models.AutoField(primary_key=True, serialize=False)),
                ('replyOfAns', models.IntegerField()),
                ('replyDesc', models.TextField()),
                ('repliedBy', models.TextField()),
                ('repliedOn', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
