# Generated by Django 3.2.9 on 2022-01-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='queSno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
