# Generated by Django 3.2.9 on 2022-01-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dislike_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
